#!/usr/bin/env node
// Interactive bootstrap. Prompts for the per-business values and writes:
//   - config/site.config.ts   (name, url, locales, defaultLocale, r2PublicBase)
//   - wrangler.toml           (R2 bucket + [vars])
//   - .dev.vars               (local secrets; gitignored)
// Stdlib only (node:readline/promises) — no dependencies.

import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { createInterface } from 'node:readline';
import { stdin, stdout } from 'node:process';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
// Async line iterator — reliable for both TTY and piped stdin.
const rl = createInterface({ input: stdin });
const lines = rl[Symbol.asyncIterator]();

async function ask(label, fallback) {
  const suffix = fallback ? ` (${fallback})` : '';
  stdout.write(`${label}${suffix}: `);
  const { value, done } = await lines.next();
  if (done) return fallback || '';
  const answer = value.trim();
  return answer || fallback || '';
}

function tsString(value) {
  return JSON.stringify(value);
}

async function main() {
  console.log('\nastro-vue-cf-starter setup\n──────────────────────────\n');

  const name = await ask('Site name', 'Acme Listings');
  const url = await ask('Site URL (no trailing slash)', 'https://example.com');
  const localesRaw = await ask('Locales (comma-separated)', 'en,es');
  const locales = localesRaw
    .split(',')
    .map((l) => l.trim())
    .filter(Boolean);
  const defaultLocale = await ask('Default locale', locales[0]);
  const r2PublicBase = await ask('R2 public base URL', 'https://media.example.com');

  const githubRepo = await ask('GitHub repo (owner/repo)', 'owner/repo');
  const githubBranch = await ask('GitHub branch', 'main');
  const githubToken = await ask('GitHub fine-grained PAT (stored in .dev.vars)', '');

  const r2Bucket = await ask('R2 bucket name', 'listings-media');
  const accessTeam = await ask('Cloudflare Access team domain', 'yourteam.cloudflareaccess.com');
  const accessAud = await ask('Cloudflare Access AUD', 'replace-with-access-application-aud');

  // ── config/site.config.ts ────────────────────────────────────────────────
  const siteConfig = `// Single source of truth for site-wide, business-agnostic settings.
// Generated by cli/setup.mjs — safe to edit by hand afterwards.

export const siteConfig = {
  name: ${tsString(name)},
  // Used for absolute URLs (sitemap, OG tags, JSON-LD). No trailing slash.
  url: ${tsString(url)},

  locales: [${locales.map(tsString).join(', ')}] as const,
  defaultLocale: ${tsString(defaultLocale)} as const,

  // Public base for R2 objects. Front end builds image URLs as
  // \`\${r2PublicBase}/\${key}\`.
  r2PublicBase: ${tsString(r2PublicBase)},

  theme: {
    // Default color mode when the visitor has no stored preference.
    defaultMode: 'system' as 'light' | 'dark' | 'system',
  },
} as const;

export type Locale = (typeof siteConfig.locales)[number];

export function isLocale(value: string): value is Locale {
  return (siteConfig.locales as readonly string[]).includes(value);
}
`;
  await writeFile(join(root, 'config/site.config.ts'), siteConfig);

  // ── wrangler.toml ─────────────────────────────────────────────────────────
  const wrangler = `name = "astro-vue-cf-starter"
compatibility_date = "2026-06-01"
pages_build_output_dir = "dist"

# R2 bucket for uploaded media (the MEDIA binding used by /api/upload).
[[r2_buckets]]
binding = "MEDIA"
bucket_name = ${tsString(r2Bucket)}

# Non-secret vars. GITHUB_TOKEN is set separately as a secret:
#   wrangler pages secret put GITHUB_TOKEN
[vars]
ENVIRONMENT = "production"
GITHUB_REPO = ${tsString(githubRepo)}
GITHUB_BRANCH = ${tsString(githubBranch)}
CF_ACCESS_TEAM_DOMAIN = ${tsString(accessTeam)}
CF_ACCESS_AUD = ${tsString(accessAud)}
`;
  await writeFile(join(root, 'wrangler.toml'), wrangler);

  // ── .dev.vars (local; gitignored) ─────────────────────────────────────────
  const devVars = `ENVIRONMENT=development
GITHUB_TOKEN=${githubToken}
GITHUB_REPO=${githubRepo}
GITHUB_BRANCH=${githubBranch}
CF_ACCESS_TEAM_DOMAIN=${accessTeam}
CF_ACCESS_AUD=${accessAud}
`;
  await writeFile(join(root, '.dev.vars'), devVars);

  console.log('\n✓ Wrote config/site.config.ts, wrangler.toml, .dev.vars');
  console.log('  Next: npm run dev  (local)  |  wrangler pages secret put GITHUB_TOKEN  (prod)\n');
}

try {
  await main();
} finally {
  rl.close();
}
